FROM gentoo/portage:latest as portage

FROM gentoo/stage3:systemd

# copy the entire portage volume in
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo

# Enable systemd
    # Install base packages
RUN emerge app-portage/gentoolkit && \
    # Install utilities needed to test Ansible
    emerge app-admin/sudo && \
    # Setup systemd
    systemd-machine-id-setup && \
    # Strip down systemd
    rm -f /etc/systemd/system/*.wants/* && \
    # Cleanup portage, downloaded source files and compile directories
    rm -rf /var/cache/distfiles /var/tmp/* && \
    # Purge logs
    rm -rf /var/log/* /var/run/log/journal/*

# Create unprivileged `ansible` user with sudo root permissions
# and membership in `DEPLOY_GROUP` for use when testing Ansible as
# as unprivileged user
ENV ANSIBLE_USER=ansible SUDO_GROUP=wheel DEPLOY_GROUP=deployer
RUN set -xe && \
    groupadd -r ${ANSIBLE_USER} && \
    groupadd -r ${DEPLOY_GROUP} && \
    useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} && \
    usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} && \
    usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} && \
    echo "%${SUDO_GROUP} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible

# Without this, init won't start the enabled services. Starting the services
# fails with one of:
#     Failed to get D-Bus connection: Operation not permitted
#     System has not been booted with systemd as init system (PID 1). Can't operate.
#     Failed to connect to bus: No such file or directory
VOLUME [ "/sys/fs/cgroup", "/run" ]

# Start via systemd
CMD ["/lib/systemd/systemd"]

# Image metadata
LABEL org.label-schema.vendor="Mesaguy" \
      org.label-schema.name="Gentoo Linux latest rolling-release boot" \
      org.label-schema.description="Image boots Gentoo Linux's latest rolling-release via systemd"
