# Source (EOL)
FROM oraclelinux:6.9

# Clean (purge) the repo cache
RUN yum -d1 -y clean all && \
  # Install docker OverlayFS plugin for yum:
  yum -d1 -y install yum-plugin-ovl && \
  # Install init scripts
  yum -d1 -y install initscripts && \
  # Update select packages to allow git to reach https sites
  yum -d1 -y update nss curl libcurl && \
  # Install utilities needed to test Ansible
  yum -d1 -y install net-tools sudo which unzip && \
  # Disable all services
  rm /etc/rc.d/rc*.d/* && \
  # Disable ttys
  mv /etc/init/serial.conf /etc/init/serial.conf.disabled && \
  mv /etc/init/tty.conf /etc/init/tty.conf.disabled && \
  mv /etc/init/start-ttys.conf /etc/init/start-ttys.conf.disabled && \
  # Clean (purge) the repo cache
  yum -d1 -y clean all && rm -rf /var/cache/yum/* && \
  # Purge logs
  rm -rf /var/log/*

# Create unprivileged `ansible` user with sudo root permissions
# and membership in `DEPLOY_GROUP` for use when testing Ansible as
# as unprivileged user
ENV ANSIBLE_USER=ansible SUDO_GROUP=wheel DEPLOY_GROUP=deployer
RUN set -xe && \
  groupadd -r ${ANSIBLE_USER} && \
  groupadd -r ${DEPLOY_GROUP} && \
  useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} && \
  usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} && \
  usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} && \
  echo "%${SUDO_GROUP} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible

# Start via init
CMD ["/sbin/init"]

# Image metadata
LABEL org.label-schema.vendor="Mesaguy" \
      org.label-schema.name="Oracle Linux 6.9 boot" \
      org.label-schema.description="Image boots Oracle Linux 6.9 via SysV init"
