# Source
FROM ubuntu:18.04

# Update repo definitions
RUN apt-get update && \
  # Install utilities needed to test Ansible
  apt-get install --no-install-recommends -y net-tools python python-apt sudo zip && \
  # Install systemd
  apt-get install --no-install-recommends -y systemd && \
  # Don't start any optional services except for the few we need.
  find /etc/systemd/system \
  /lib/systemd/system \
  -path '*.wants/*' \
  -not -name '*journald*' \
  -not -name '*systemd-tmpfiles*' \
  -not -name '*systemd-user-sessions*' \
  -exec rm \{\} \; && \
  systemctl set-default multi-user.target && \
  # Clean (purge) the repo cache
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  # Purge logs
  rm -rf /var/log/* /var/run/log/journal

# Create unprivileged `ansible` user with sudo root permissions
# and membership in `DEPLOY_GROUP` for use when testing Ansible as
# as unprivileged user
ENV ANSIBLE_USER=ansible SUDO_GROUP=adm DEPLOY_GROUP=deployer
RUN set -xe && \
  groupadd -r ${ANSIBLE_USER} && \
  groupadd -r ${DEPLOY_GROUP} && \
  useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} && \
  usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} && \
  usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} && \
  echo "%${SUDO_GROUP} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible

# Without this, init won't start the enabled services. Starting the services
# fails with one of:
#     Failed to get D-Bus connection: Operation not permitted
#     System has not been booted with systemd as init system (PID 1). Can't operate.
#     Failed to connect to bus: No such file or directory
VOLUME [ "/sys/fs/cgroup", "/run" ]

# Start via systemd
CMD ["/lib/systemd/systemd"]

# Image metadata
LABEL org.label-schema.vendor="Mesaguy" \
      org.label-schema.name="Ubuntu Linux 18.04 (Bionic Beaver) boot" \
      org.label-schema.description="Image boots Ubuntu Linux 18.04 (Bionic Beaver) via systemd"
