# Source (EOL)
FROM oraclelinux:5.11

# Clean (purge) the repo cache
RUN yum -d1 -y clean all && \
  # Update all packages
  yum -d1 -y update && \
  # Install utilities needed to test Ansible
  yum -d1 -y install net-tools sudo && \
  # Disable all services
  rm /etc/rc.d/rc*.d/* && \
  # Clean (purge) the repo cache
  yum -d1 -y clean all && rm -rf /var/cache/yum/* && \
  # Purge logs
  rm -rf /var/log/*

# Create unprivileged `ansible` user with sudo root permissions
# and membership in `DEPLOY_GROUP` for use when testing Ansible as
# as unprivileged user
ENV ANSIBLE_USER=ansible SUDO_GROUP=wheel DEPLOY_GROUP=deployer
RUN set -xe && \
  groupadd -r ${ANSIBLE_USER} && \
  groupadd -r ${DEPLOY_GROUP} && \
  useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} && \
  usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} && \
  usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} && \
  echo "%${SUDO_GROUP} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Start via init
CMD ["/sbin/init"]

# Image metadata
LABEL org.label-schema.vendor="Mesaguy" \
      org.label-schema.name="Oracle Linux 5.11 boot" \
      org.label-schema.description="Image boots Oracle Linux 5.11 via SysV init"
