# Source (EOL)
FROM oraclelinux:8.0

# Clean (purge) the repo cache
RUN dnf -y clean all && \
  # Replace broken systemd, ships with missing libsystemd-shared-239.so
  dnf -y reinstall systemd && \
  # Install dbus daemon for systemd
  dnf -y install dbus-daemon && \
  # Install utilities needed to test Ansible
  yum -d1 -y install net-tools sudo && \
  # Strip down systemd
  for f in /lib/systemd/system/sysinit.target.wants/* ; do if [ "$(basename "$f")" != "systemd-tmpfiles-setup.service" ] ; then rm -f "$f" ; fi ; done && \
  rm -f /lib/systemd/system/multi-user.target.wants/* && \
  rm -f /etc/systemd/system/*.wants/* && \
  rm -f /lib/systemd/system/local-fs.target.wants/* && \
  rm -f /lib/systemd/system/sockets.target.wants/*udev* && \
  rm -f /lib/systemd/system/sockets.target.wants/*initctl* && \
  rm -f /lib/systemd/system/basic.target.wants/* && \
  rm -f /lib/systemd/system/anaconda.target.wants/* && \
  # Clean (purge) the repo cache
  dnf -y clean all && rm -rf /var/cache/dnf/* /var/cache/yum/* && \
  # Purge logs
  rm -rf /var/log/* /var/run/log/journal

# Create unprivileged `ansible` user with sudo root permissions
# and membership in `DEPLOY_GROUP` for use when testing Ansible as
# as unprivileged user
ENV ANSIBLE_USER=ansible SUDO_GROUP=wheel DEPLOY_GROUP=deployer
RUN set -xe && \
  groupadd -r ${ANSIBLE_USER} && \
  groupadd -r ${DEPLOY_GROUP} && \
  useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} && \
  usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} && \
  usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} && \
  echo "%${SUDO_GROUP} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible

# Without this, init won't start the enabled services. Starting the services
# fails with one of:
#     Failed to get D-Bus connection: Operation not permitted
#     System has not been booted with systemd as init system (PID 1). Can't operate.
#     Failed to connect to bus: No such file or directory
VOLUME [ "/sys/fs/cgroup", "/run" ]

# Start via systemd
CMD ["/usr/lib/systemd/systemd"]

# Image metadata
LABEL org.label-schema.vendor="Mesaguy" \
      org.label-schema.name="Oracle Linux 8.0 boot" \
      org.label-schema.description="Image boots Oracle Linux 8.0 systemd"
