# Source
FROM opensuse/leap:15.0

# Install software and update
RUN zypper --non-interactive dup && \
  # Install OS identifiers
  zypper --non-interactive install --no-confirm openSUSE-release && \
  # Install systemd && \
  zypper --non-interactive install systemd && \
  # Install utilities needed to test Ansible
  zypper --non-interactive install net-tools python python-xml sudo system-group-wheel && \
  # Strip down systemd
  rm -f /usr/lib/systemd/system/multi-user.target.wants/* && \
  rm -f /etc/systemd/system/*.wants/* && \
  rm -f /usr/lib/systemd/system/local-fs.target.wants/* && \
  rm -f /usr/lib/systemd/system/sockets.target.wants/*udev* && \
  rm -f /usr/lib/systemd/system/sockets.target.wants/*initctl* && \
  rm -f /usr/lib/systemd/system/basic.target.wants/* && \
  rm -f /usr/lib/systemd/system/anaconda.target.wants/* && \
  # Clean (purge) the repo cache
  zypper --non-interactive clean --all && \
  # Purge logs
  rm -rf /var/log/* /var/run/log/journal

# Create unprivileged `ansible` user with sudo root permissions
# and membership in `DEPLOY_GROUP` for use when testing Ansible as
# as unprivileged user
ENV ANSIBLE_USER=ansible SUDO_GROUP=wheel DEPLOY_GROUP=deployer
RUN set -xe && \
  groupadd -r ${ANSIBLE_USER} && \
  groupadd -r ${DEPLOY_GROUP} && \
  useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} && \
  usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} && \
  usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} && \
  echo "%${SUDO_GROUP} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible

# Without this, init won't start the enabled services. Starting the services
# fails with one of:
#     Failed to get D-Bus connection: Operation not permitted
#     System has not been booted with systemd as init system (PID 1). Can't operate.
#     Failed to connect to bus: No such file or directory
VOLUME [ "/sys/fs/cgroup", "/run" ]

# Start via systemd
CMD ["/usr/lib/systemd/systemd"]

# Image metadata
LABEL org.label-schema.vendor="Mesaguy" \
      org.label-schema.name="OpenSUSE Linux leap 15.0 boot" \
      org.label-schema.description="Image boots OpenSUSE Linux leap 15.0 via systemd"
